### ISSUE TITLE
Customer resolver not working on initial load of lazy route

### ISSUE THREAD

**Issue by dottodot** [exalif/angular-libs#37]
I've have the following setup in a lazy module

```
  {
    path: ':catid/:slug',
    component: ShopViewComponent,
    data: {
      breadcrumbs: ShopBreadCrumbResolver
    },
    resolve: {
      product: ShopProductResolver
    }
  }
```
but the ShopBreadCrumbResolver only seem to work when navigating using `routerLink`. If I refresh the page the `ShopBreadCrumbResolver` isn't triggered and no breadcrumb is displayed.

**Comment by blackholegalaxy** [comment]
We use a custom resolver on production on lazy loaded routes and it works well when deeplinking to a page. Could you provide your resolver code so we can check on that?

**Comment by dottodot** [comment]
This is my customer resolver

```
@Injectable({ providedIn: 'root' })
export class ShopBreadCrumbResolver extends BreadcrumbsResolver {
  constructor() {
    super();
  }
  resolve(
    route: ActivatedRouteSnapshot,
    state: RouterStateSnapshot
  ): Observable<Breadcrumb[]> {
    const product: Product = route.data.product;
    const crumbs: Breadcrumb[] = [
      {
        text: product.categories[0].title,
        path: `${this.getFullPath(route.parent)}/${product.categories[0].slug}`
      },
      {
        text: product.title,
        path: `${this.getFullPath(route.parent)}/${
          product.categories[0].slug
        }/${product.slug}`
      }
    ];

    return of(crumbs);
  }
}
```

**Comment by blackholegalaxy** [comment]
Since you use a custom resolver, why not move your resolve() logic into this resolver? I guess resolved values arrives after the breadcrumbs resolved did its job.

**Comment by dottodot** [comment]
I don't think that is it. I've change to not rely on the other resolver the same thing happens.

```
@Injectable({ providedIn: 'root' })
export class ShopBreadCrumbResolver extends BreadcrumbsResolver {
  constructor() {
    super();
  }
  resolve(
    route: ActivatedRouteSnapshot,
    state: RouterStateSnapshot
  ): Observable<Breadcrumb[]> {
    const crumbs: Breadcrumb[] = [
      {
        text: 'Test',
        path: ''
      }
    ];

    return of(crumbs);
  }
}
```

**Comment by blackholegalaxy** [comment]
can you provide a repro on stackblitz? I double check on our main app and the breadcrumbs display properly event on entity deep linking and refresh. It uses the id from route params then call our ngrx store to populate the breadcrumb data with no error.

**Comment by dottodot** [comment]
OK so when I've provide it in my lazy module I get a error but the same result. 

When I navigate using routerlink I get the following error, I don't get this error when I access the url directly. Oddly the breadcrumb shows when I get the error and doesn't when I don't get the error which is a bit puzzling.

```
zone-evergreen.js:172 Uncaught NullInjectorError: StaticInjectorError(AppModule)[ShopBreadCrumbResolver]: 
  StaticInjectorError(Platform: core)[ShopBreadCrumbResolver]: 
    NullInjectorError: No provider for ShopBreadCrumbResolver!
    at NullInjector.get (https://localhost:4200/vendor.js:53613:27)
    at resolveToken (https://localhost:4200/vendor.js:68530:24)
    at tryResolveToken (https://localhost:4200/vendor.js:68456:16)
    at StaticInjector.get (https://localhost:4200/vendor.js:68306:20)
    at resolveToken (https://localhost:4200/vendor.js:68530:24)
    at tryResolveToken (https://localhost:4200/vendor.js:68456:16)
    at StaticInjector.get (https://localhost:4200/vendor.js:68306:20)
    at resolveNgModuleDep (https://localhost:4200/vendor.js:79493:29)
    at NgModuleRef_.get (https://localhost:4200/vendor.js:80559:16)
    at BreadcrumbsService._resolveCrumbs (https://localhost:4200/vendor.js:119888:43)
    at BreadcrumbsService._resolveCrumbs (https://localhost:4200/vendor.js:119900:89)
    at BreadcrumbsService._resolveCrumbs (https://localhost:4200/vendor.js:119900:89)
    at BreadcrumbsService._resolveCrumbs (https://localhost:4200/vendor.js:119900:89)
    at SafeSubscriber._next (https://localhost:4200/vendor.js:119862:18)
    at SafeSubscriber.__tryOrUnsub (https://localhost:4200/vendor.js:158758:16)
    at SafeSubscriber.next (https://localhost:4200/vendor.js:158697:22)
    at Subscriber._next (https://localhost:4200/vendor.js:158647:26)
    at Subscriber.next (https://localhost:4200/vendor.js:158624:18)
    at FilterSubscriber._next (https://localhost:4200/vendor.js:162632:30)
    at FilterSubscriber.next (https://localhost:4200/vendor.js:158624:18)
    at Subject.next (https://localhost:4200/vendor.js:158410:25)
    at SafeSubscriber._next (https://localhost:4200/vendor.js:117139:18)
    at SafeSubscriber.__tryOrUnsub (https://localhost:4200/vendor.js:158758:16)
    at SafeSubscriber.next (https://localhost:4200/vendor.js:158697:22)
    at Subscriber._next (https://localhost:4200/vendor.js:158647:26)
    at Subscriber.next (https://localhost:4200/vendor.js:158624:18)
    at SwitchMapSubscriber.notifyNext (https://localhost:4200/vendor.js:165156:26)
    at InnerSubscriber._next (https://localhost:4200/vendor.js:157919:21)
    at InnerSubscriber.next (https://localhost:4200/vendor.js:158624:18)
    at CatchSubscriber._next (https://localhost:4200/vendor.js:158647:26)
    at CatchSubscriber.next (https://localhost:4200/vendor.js:158624:18)
    at FinallySubscriber._next (https://localhost:4200/vendor.js:158647:26)
    at FinallySubscriber.next (https://localhost:4200/vendor.js:158624:18)
    at TapSubscriber._next (https://localhost:4200/vendor.js:165480:26)
    at TapSubscriber.next (https://localhost:4200/vendor.js:158624:18)
    at MapSubscriber._next (https://localhost:4200/vendor.js:163119:26)
    at MapSubscriber.next (https://localhost:4200/vendor.js:158624:18)
    at TapSubscriber._next (https://localhost:4200/vendor.js:165480:26)
    at TapSubscriber.next (https://localhost:4200/vendor.js:158624:18)
    at MapSubscriber._next (https://localhost:4200/vendor.js:163119:26)
    at MapSubscriber.next (https://localhost:4200/vendor.js:158624:18)
    at SwitchMapSubscriber.notifyNext (https://localhost:4200/vendor.js:165156:26)
    at InnerSubscriber._next (https://localhost:4200/vendor.js:157919:21)
    at InnerSubscriber.next (https://localhost:4200/vendor.js:158624:18)
    at MapSubscriber._next (https://localhost:4200/vendor.js:163119:26)
    at MapSubscriber.next (https://localhost:4200/vendor.js:158624:18)
    at Observable._subscribe (https://localhost:4200/vendor.js:168012:20)
    at Observable._trySubscribe (https://localhost:4200/vendor.js:158080:25)
    at Observable.subscribe (https://localhost:4200/vendor.js:158066:22)
    at MapOperator.call (https://localhost:4200/vendor.js:163100:23)
```

**Comment by blackholegalaxy** [comment]
can you try to provide the resolver using the old method, like listing the resolver within providers array in the module?

**Comment by dottodot** [comment]
That's exactly what I did when I got the error in my previous post

**Comment by blackholegalaxy** [comment]
If you didn't manage to get it working, could you maybe send a repro on stackblitz?

**Comment by dottodot** [comment]
I've found a resolution to this problem. 

I had a custom component to display the breadcrumbs and was subscribing to the breadcrumbs service inside it. i.e

```
  public crumbs$: Observable<
    Breadcrumb[]
  > = this.breadcrumbsService.getCrumbs();
  constructor(private breadcrumbsService: BreadcrumbsService) {}
```
but if I move that into a service instead I don't get the issue.

**Comment by blackholegalaxy** [comment]
Ok so you have certainly had a dependency injection problem on that. If it's not related to library, can we close this issue?
